# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nudge < Formula
  desc "Accountability CLI with real consequences — set deadlines, add secrets, face punishments"
  homepage "https://github.com/neilsanghrajka/nudge"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.3.0/nudge_darwin_amd64.tar.gz"
      sha256 "453d6f262380057aaa4890dfaa7ebe4392da35c14d43fd97fcb98bc81291f3ac"

      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.3.0/nudge_darwin_arm64.tar.gz"
      sha256 "04ece09de61399e728252e38c70a27d9fae95677e4d4afcdcac38e5120d5193e"

      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.3.0/nudge_linux_amd64.tar.gz"
      sha256 "7fedbd773ffe60446f6f1dac8f7cc37d63a13ce9732e6e0f30b6390cd4df9c39"
      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.3.0/nudge_linux_arm64.tar.gz"
      sha256 "83198b9270fa1babb356379fb9da14eb38b0178b60625b5ac2f210da27eb4366"
      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  test do
    system "#{bin}/nudge", "version"
  end
end
