# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nudge < Formula
  desc "Accountability CLI with real consequences — set deadlines, add secrets, face punishments"
  homepage "https://github.com/neilsanghrajka/nudge"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.2.0/nudge_darwin_amd64.tar.gz"
      sha256 "6074b7ffc4f6e5a898c72714f2c6a7a89e693ae5d09c06cbdc2974eaf860dc36"

      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.2.0/nudge_darwin_arm64.tar.gz"
      sha256 "07d601ef37d4f56ca73a9a9139f953720b914ae2f73978352214eb1e6cd2102b"

      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.2.0/nudge_linux_amd64.tar.gz"
      sha256 "40279459af60c298cb5fa84daed487b8b083dad1760cf71f9174e41f4709195d"
      define_method(:install) do
        bin.install "nudge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilsanghrajka/nudge/releases/download/v0.2.0/nudge_linux_arm64.tar.gz"
      sha256 "4c7e7d2a443d4dc15925d20d5b804ef675860bc9261edaa2a65cc155ef75f589"
      define_method(:install) do
        bin.install "nudge"
      end
    end
  end

  test do
    system "#{bin}/nudge", "version"
  end
end
